name: New policy cron job
on:
  schedule:
    - cron: '*/25 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: New policy cron job
        run: |
          curl --request GET \
          --url 'https://sles-api-logic.d38kjhy28eygf8.amplifyapp.com/api/jobs/search_new_policy' \
